
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev

logging.level.org.springframework.security=INFO
spring.jackson.serialization.indent_output=true
spring.jackson.default-property-inclusion=non_null
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.security.user.name=admin
spring.security.user.password=admin


jwt.secret=SuperSecureKeyThatIsLongEnoughToBeSafeForHS512!IUFOHUDHIULDKLJHKLDLUIHFIDSLUIILFUKLLjbkjdhdlskjklhjligkjhvnkjH
jwt.expirationMs=3600000
spring.main.allow-bean-definition-overriding=true
spring.r2dbc.enabled=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=user-profile-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.example.DTO
spring.kafka.consumer.properties.spring.json.use.type.headers=false



spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer



logging.file.name=logs/app.log
logging.level.root=INFO

logging.level.org.springframework=INFO




spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest